import 'package:erp_app/src/recursos/movimientos_constants.dart';
import 'package:erp_app/src/shell/models.dart';

const List<SectionField> movimientosVistaFormFields = [
  SectionField(
    sectionId: 'movimientos',
    id: 'idpedido',
    label: 'Pedido',
    readOnly: true,
    visible: false,
  ),
  SectionField(
    sectionId: 'movimientos',
    id: 'codigo',
    label: 'Movimiento',
    readOnly: true,
  ),
  SectionField(
    sectionId: 'movimientos',
    id: 'observacion',
    label: 'Observación',
  ),
  SectionField(
    sectionId: 'movimientos',
    id: 'es_provincia',
    label: '¿Es provincia?',
    staticOptions: ['false', 'true'],
    defaultValue: 'false',
  ),
  SectionField(
    sectionId: 'movimientos',
    id: 'idbase',
    label: 'Base',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
  ),
  SectionField(
    sectionId: 'movimientos',
    id: kMovDestinoLimaDireccionField,
    label: 'Dirección',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'direccion',
    referenceLabelColumn: 'direccion',
    referenceSectionId: 'direccion_form',
    visibleWhenField: 'es_provincia',
    visibleWhenEquals: 'false',
  ),
  SectionField(
    sectionId: 'movimientos',
    id: kMovDestinoLimaContactoField,
    label: 'Número que recibe',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'numrecibe',
    referenceLabelColumn: 'numero',
    referenceSectionId: 'numrecibe_form',
    visibleWhenField: 'es_provincia',
    visibleWhenEquals: 'false',
  ),
  SectionField(
    sectionId: 'movimientos',
    id: kMovDestinoProvinciaDireccionField,
    label: 'Dirección cliente',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'direccion_provincia',
    referenceLabelColumn: 'lugar_llegada',
    referenceSectionId: 'direccion_provincia_form',
    visibleWhenField: 'es_provincia',
    visibleWhenEquals: 'true',
  ),
];

const List<SectionField> movimientosLecturaFormFields = [
  SectionField(
    sectionId: 'movimientos',
    id: 'id',
    label: 'ID',
    readOnly: true,
    visible: false,
  ),
  SectionField(
    sectionId: 'movimientos',
    id: 'codigo',
    label: 'Movimiento',
    readOnly: true,
  ),
  SectionField(
    sectionId: 'movimientos',
    id: 'idbase',
    label: 'Base',
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
    required: true,
  ),
];
