import 'package:erp_app/src/recursos/movimientos_constants.dart';
import 'package:erp_app/src/shell/models.dart';

/// Formulario usado cuando los movimientos se crean desde un pedido.
const List<SectionField> movimientosInlineFields = [
  SectionField(
    sectionId: 'pedidos_movimientos',
    id: 'idpedido',
    label: 'Pedido',
    readOnly: true,
    visible: false,
  ),
  SectionField(
    sectionId: 'pedidos_movimientos',
    id: 'observacion',
    label: 'Observación',
  ),
  SectionField(
    sectionId: 'pedidos_movimientos',
    id: 'es_provincia',
    label: '¿Es provincia?',
    staticOptions: ['false', 'true'],
    defaultValue: 'false',
  ),
  SectionField(
    sectionId: 'pedidos_movimientos',
    id: 'idbase',
    label: 'Base',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
  ),
  SectionField(
    sectionId: 'pedidos_movimientos',
    id: kMovDestinoLimaDireccionField,
    label: 'Dirección',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'direccion',
    referenceLabelColumn: 'direccion',
    referenceSectionId: 'direccion_form',
    visibleWhenField: 'es_provincia',
    visibleWhenEquals: 'false',
  ),
  SectionField(
    sectionId: 'pedidos_movimientos',
    id: kMovDestinoLimaContactoField,
    label: 'Número que recibe',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'numrecibe',
    referenceLabelColumn: 'numero',
    referenceSectionId: 'numrecibe_form',
    visibleWhenField: 'es_provincia',
    visibleWhenEquals: 'false',
  ),
  SectionField(
    sectionId: 'pedidos_movimientos',
    id: kMovDestinoProvinciaDireccionField,
    label: 'Dirección cliente',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'direccion_provincia',
    referenceLabelColumn: 'lugar_llegada',
    referenceSectionId: 'direccion_provincia_form',
    visibleWhenField: 'es_provincia',
    visibleWhenEquals: 'true',
  ),
];
