import 'package:erp_app/src/shell/models.dart';

final List<SectionField> finanzasMovimientosFormFields = [
  SectionField(
    sectionId: 'finanzas_movimientos',
    id: 'tipo',
    label: 'Tipo',
    required: true,
    staticOptions: ['ingreso', 'gasto', 'ajuste', 'transferencia'],
    defaultValue: 'gasto',
    order: 1,
  ),
  SectionField(
    sectionId: 'finanzas_movimientos',
    id: 'descripcion',
    label: 'Descripción',
    required: true,
    order: 2,
  ),
  SectionField(
    sectionId: 'finanzas_movimientos',
    id: 'monto',
    label: 'Monto',
    required: true,
    dataType: 'numeric',
    order: 3,
  ),
  SectionField(
    sectionId: 'finanzas_movimientos',
    id: 'idcuenta_contable',
    label: 'Cuenta contable',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'cuentas_contables',
    referenceLabelColumn: 'nombre',
    visibleWhenField: 'tipo',
    visibleWhenEquals: 'ingreso,gasto,ajuste',
    order: 4,
  ),
  SectionField(
    sectionId: 'finanzas_movimientos',
    id: 'idcuenta_origen',
    label: 'Cuenta origen',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'v_cuentas_bancarias_visibles',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'cuentas_bancarias_form',
    visibleWhenField: 'tipo',
    visibleWhenEquals: 'gasto,ajuste,transferencia',
    order: 5,
  ),
  SectionField(
    sectionId: 'finanzas_movimientos',
    id: 'idcuenta_destino',
    label: 'Cuenta destino',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'v_cuentas_bancarias_visibles',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'cuentas_bancarias_form',
    visibleWhenField: 'tipo',
    visibleWhenEquals: 'ingreso,transferencia',
    order: 6,
  ),
  SectionField(
    sectionId: 'finanzas_movimientos',
    id: 'observacion',
    label: 'Observación',
    order: 7,
  ),
];

final List<SectionField> finanzasGastosFormFields = [
  SectionField(
    sectionId: 'finanzas_gastos',
    id: 'registrado_at',
    label: 'Fecha',
    required: true,
    widgetType: 'datetime',
    defaultValue: 'now',
    order: 1,
  ),
  SectionField(
    sectionId: 'finanzas_gastos',
    id: 'idcuenta_contable',
    label: 'Cuenta contable',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'v_cuentas_contables_gasto_tipos',
    referenceLabelColumn: 'nombre_display',
    order: 2,
  ),
  SectionField(
    sectionId: 'finanzas_gastos',
    id: 'descripcion',
    label: 'Descripción',
    required: true,
    order: 3,
  ),
  SectionField(
    sectionId: 'finanzas_gastos',
    id: 'monto',
    label: 'Monto',
    required: true,
    dataType: 'numeric',
    order: 4,
  ),
  SectionField(
    sectionId: 'finanzas_gastos',
    id: 'idcuenta',
    label: 'Cuenta bancaria',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'v_cuentas_bancarias_visibles',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'cuentas_bancarias_form',
    order: 5,
  ),
  SectionField(
    sectionId: 'finanzas_gastos',
    id: 'idpedido',
    label: 'Referencia',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'v_pedido_vistageneral',
    referenceLabelColumn: 'cliente_nombre',
    referenceSectionId: 'pedidos_tabla',
    order: 6,
  ),
];
