import 'package:erp_app/src/shell/models.dart';

const List<String> _diasSemana = [
  'lunes',
  'martes',
  'miercoles',
  'jueves',
  'viernes',
  'sabado',
  'domingo',
];

const List<SectionField> asistenciasSlotsFormFields = [
  SectionField(
    sectionId: 'asistencias_slots',
    id: 'nombre',
    label: 'Nombre',
    required: true,
    order: 1,
  ),
  SectionField(
    sectionId: 'asistencias_slots',
    id: 'hora',
    label: 'Hora (HH:MM)',
    required: true,
    order: 2,
  ),
  SectionField(
    sectionId: 'asistencias_slots',
    id: 'descripcion',
    label: 'Descripcion',
    order: 3,
  ),
  SectionField(
    sectionId: 'asistencias_slots',
    id: 'activo',
    label: 'Activo',
    staticOptions: ['true', 'false'],
    defaultValue: 'true',
    order: 4,
  ),
];

const List<SectionField> asistenciasBaseSlotsFormFields = [
  SectionField(
    sectionId: 'asistencias_base_slots',
    id: 'idbase',
    label: 'Base',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
    order: 1,
  ),
  SectionField(
    sectionId: 'asistencias_base_slots',
    id: 'dia_semana',
    label: 'Dia',
    required: true,
    widgetType: 'select',
    staticOptions: _diasSemana,
    defaultValue: 'lunes',
    order: 2,
  ),
  SectionField(
    sectionId: 'asistencias_base_slots',
    id: 'idslot',
    label: 'Slot',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'asistencias_slots',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'asistencias_slots',
    order: 3,
  ),
  SectionField(
    sectionId: 'asistencias_base_slots',
    id: 'activo',
    label: 'Activo',
    staticOptions: ['true', 'false'],
    defaultValue: 'true',
    order: 4,
  ),
];

const List<SectionField> asistenciasPendientesFormFields = [
  SectionField(
    sectionId: 'asistencias_pendientes',
    id: 'idbase',
    label: 'Base',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
    order: 1,
  ),
  SectionField(
    sectionId: 'asistencias_pendientes',
    id: 'idslot',
    label: 'Slot',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'asistencias_slots',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'asistencias_slots',
    order: 2,
  ),
  SectionField(
    sectionId: 'asistencias_pendientes',
    id: 'fecha',
    label: 'Fecha',
    widgetType: 'datetime',
    required: true,
    order: 3,
  ),
  SectionField(
    sectionId: 'asistencias_pendientes',
    id: 'estado',
    label: 'Estado',
    widgetType: 'select',
    staticOptions: ['falta', 'asistio', 'justificado'],
    defaultValue: 'falta',
    order: 4,
  ),
  SectionField(
    sectionId: 'asistencias_pendientes',
    id: 'observacion',
    label: 'Observacion',
    order: 5,
  ),
];

const List<SectionField> asistenciasPermisosFormFields = [
  SectionField(
    sectionId: 'asistencias_permisos',
    id: 'idbase',
    label: 'Base',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
    order: 1,
  ),
  SectionField(
    sectionId: 'asistencias_permisos',
    id: 'idslot',
    label: 'Slot',
    required: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'asistencias_slots',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'asistencias_slots',
    order: 2,
  ),
  SectionField(
    sectionId: 'asistencias_permisos',
    id: 'tipo',
    label: 'Tipo',
    widgetType: 'select',
    staticOptions: ['ausencia', 'reemplazo'],
    defaultValue: 'ausencia',
    order: 3,
  ),
  SectionField(
    sectionId: 'asistencias_permisos',
    id: 'fecha',
    label: 'Fecha (opcional)',
    widgetType: 'datetime',
    order: 4,
  ),
  SectionField(
    sectionId: 'asistencias_permisos',
    id: 'dia_semana',
    label: 'Dia (opcional)',
    widgetType: 'select',
    staticOptions: _diasSemana,
    order: 5,
  ),
  SectionField(
    sectionId: 'asistencias_permisos',
    id: 'motivo',
    label: 'Motivo',
    order: 6,
  ),
  SectionField(
    sectionId: 'asistencias_permisos',
    id: 'activo',
    label: 'Activo',
    staticOptions: ['true', 'false'],
    defaultValue: 'true',
    order: 7,
  ),
];
