import 'package:erp_app/src/shell/models.dart';

const List<SectionField> viajesIncidentesVistaFormFields = [
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'idviaje_detalle',
    label: 'Detalle del viaje',
    readOnly: true,
    visible: false,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'idmovimiento',
    label: 'Movimiento',
    readOnly: true,
    visible: false,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'movimiento_codigo',
    label: 'Movimiento',
    readOnly: true,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'idpedido',
    label: 'Pedido',
    readOnly: true,
    visible: false,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'idbase',
    label: 'Base',
    readOnly: true,
    visible: false,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'cliente_nombre',
    label: 'Cliente',
    readOnly: true,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'cliente_numero',
    label: 'Número cliente',
    readOnly: true,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'contacto_display',
    label: 'Contacto',
    readOnly: true,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'direccion_texto',
    label: 'Dirección',
    readOnly: true,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'direccion_referencia',
    label: 'Referencia',
    readOnly: true,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'tipo',
    label: 'Tipo',
    required: true,
    staticOptions: ['robado', 'danado'],
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'observacion',
    label: 'Observación',
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'productos_afectados',
    label: 'Productos afectados',
    readOnly: true,
    visible: false,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'cantidad_afectada',
    label: 'Cantidad afectada',
    readOnly: true,
    visible: false,
    persist: false,
  ),
  SectionField(
    sectionId: 'viajes_incidentes',
    id: 'registrado_at',
    label: 'Registrado',
    readOnly: true,
    visible: false,
    widgetType: 'datetime',
    persist: false,
  ),
];
