import 'package:erp_app/src/shell/models.dart';

const List<SectionField> comunicacionesBaseFormFields = [
  SectionField(
    sectionId: 'comunicaciones_base',
    id: 'idbase',
    label: 'Base',
    required: true,
    readOnly: true,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
    order: 1,
  ),
  SectionField(
    sectionId: 'comunicaciones_base',
    id: 'asunto',
    label: 'Asunto',
    required: true,
    order: 2,
  ),
  SectionField(
    sectionId: 'comunicaciones_base',
    id: 'mensaje',
    label: 'Mensaje',
    required: true,
    order: 3,
  ),
  SectionField(
    sectionId: 'comunicaciones_base',
    id: 'prioridad',
    label: 'Prioridad',
    required: true,
    staticOptions: ['baja', 'media', 'alta'],
    defaultValue: 'media',
    order: 4,
  ),
  SectionField(
    sectionId: 'comunicaciones_base',
    id: 'estado',
    label: 'Estado',
    readOnly: true,
    staticOptions: ['pendiente', 'finalizado'],
    defaultValue: 'pendiente',
    order: 5,
  ),
];

const List<SectionField> comunicacionesVistaFormFields = [
  SectionField(
    sectionId: 'comunicaciones',
    id: 'idbase',
    label: 'Base',
    readOnly: true,
    persist: false,
    widgetType: 'reference',
    referenceSchema: 'public',
    referenceRelation: 'bases',
    referenceLabelColumn: 'nombre',
    referenceSectionId: 'bases_form',
    order: 1,
  ),
  SectionField(
    sectionId: 'comunicaciones',
    id: 'asunto',
    label: 'Asunto',
    readOnly: true,
    persist: false,
    order: 2,
  ),
  SectionField(
    sectionId: 'comunicaciones',
    id: 'mensaje',
    label: 'Mensaje',
    readOnly: true,
    persist: false,
    order: 3,
  ),
  SectionField(
    sectionId: 'comunicaciones',
    id: 'prioridad',
    label: 'Prioridad',
    readOnly: true,
    persist: false,
    staticOptions: ['baja', 'media', 'alta'],
    order: 4,
  ),
  SectionField(
    sectionId: 'comunicaciones',
    id: 'estado',
    label: 'Estado',
    required: true,
    staticOptions: ['pendiente', 'finalizado'],
    order: 5,
  ),
  SectionField(
    sectionId: 'comunicaciones',
    id: 'registrado_at',
    label: 'Registrado',
    readOnly: true,
    persist: false,
    widgetType: 'datetime',
    order: 6,
  ),
];
